### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by dsdebastiani** [tomymolina/generator-android-clean-architecture#1]
I received the following error:

```
/usr/local/lib/node_modules/generator-android-clean-architecture/generators/app/index.js:94
    copyFiles.forEach(([src, dest = src]) => {
                       ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as android-clean-architecture:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:262:16)
```
Node version: `v4.2.6`

**Comment by marmol-dev** [comment]
You need Node v6 or greater.
